openapi: 3.0.1
info:
  title: OpenAPI definition
  version: v0
servers:
  - url: 'http://localhost:8080'
    description: Generated server url
paths:
  /:
    get:
      tags:
        - hello-controller
      operationId: index
      responses:
        '200':
          description: OK
          content:
            '*/*':
              schema:
                type: string
    put:
      tags:
        - hello-controller
      operationId: index_6
      responses:
        '200':
          description: OK
          content:
            '*/*':
              schema:
                type: string
    post:
      tags:
        - hello-controller
      operationId: index_1
      responses:
        '200':
          description: OK
          content:
            '*/*':
              schema:
                type: string
    delete:
      tags:
        - hello-controller
      operationId: index_4
      responses:
        '200':
          description: OK
          content:
            '*/*':
              schema:
                type: string
    options:
      tags:
        - hello-controller
      operationId: index_3
      responses:
        '200':
          description: OK
          content:
            '*/*':
              schema:
                type: string
    head:
      tags:
        - hello-controller
      operationId: index_5
      responses:
        '200':
          description: OK
          content:
            '*/*':
              schema:
                type: string
    patch:
      tags:
        - hello-controller
      operationId: index_2
      responses:
        '200':
          description: OK
          content:
            '*/*':
              schema:
                type: string
  /java11/:
    get:
      tags:
        - java-11-controller
      operationId: index_7
      responses:
        '200':
          description: OK
          content:
            '*/*':
              schema:
                type: string
    put:
      tags:
        - java-11-controller
      operationId: index_13
      responses:
        '200':
          description: OK
          content:
            '*/*':
              schema:
                type: string
    post:
      tags:
        - java-11-controller
      operationId: index_8
      responses:
        '200':
          description: OK
          content:
            '*/*':
              schema:
                type: string
    delete:
      tags:
        - java-11-controller
      operationId: index_11
      responses:
        '200':
          description: OK
          content:
            '*/*':
              schema:
                type: string
    options:
      tags:
        - java-11-controller
      operationId: index_10
      responses:
        '200':
          description: OK
          content:
            '*/*':
              schema:
                type: string
    head:
      tags:
        - java-11-controller
      operationId: index_12
      responses:
        '200':
          description: OK
          content:
            '*/*':
              schema:
                type: string
    patch:
      tags:
        - java-11-controller
      operationId: index_9
      responses:
        '200':
          description: OK
          content:
            '*/*':
              schema:
                type: string
components: {}
